version: '3.1'

services:

  # API Merchant
  api_merchant:
    restart: always
    container_name: api_merchant
    build:
      context: .
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 2358:2345
    depends_on:
      - db
    networks:
      - local

  # Elasticsearch untuk API Merchant
  elasticsearch_merchant:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.13.3'
    container_name: elasticsearch_merchant
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9400:9200"
    volumes:
      - esdata_merchant:/usr/share/elasticsearch/data
    networks:
      - local

  # Database (Shared by Both)
  db:
    container_name: db_main
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - local

volumes:
  esdata_merchant:
    driver: local
  db_data:
    driver: local

networks:
  local:
    driver: bridge
