version: '3.1'

services:
  api_merchant:
    restart: always
    container_name: api_merchant
    build:
      context: ./repo-api-merchant
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - ./repo-api-merchant:/app
    ports:
      - 2358:2345
    depends_on:
      - db
    networks:
      - shared_network

  db:
    container_name: db_merchant
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=release_dv_cp
    volumes:
      - db_merchant_data:/var/lib/postgresql
    ports:
      - "5431:5432"
    networks:
      - shared_network

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.13.3'
    container_name: elasticsearch_merchant
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9400:9200"
    volumes:
      - es_merchant_data:/usr/share/elasticsearch/data

volumes:
  db_merchant_data:
  es_merchant_data:

networks:
  shared_network:
    driver: bridge
