version: '3.1'

services:
  api_merchant:
    restart: always
    container_name: api_merchant
    build:
      context: ./api_merchant
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - ./api_merchant:/app
    ports:
      - "2358:2345"
    depends_on:
      - db
    networks:
      - local

  db:
    container_name: db_merchant
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - local

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.13.3'
    container_name: elasticsearchmerchant
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9400:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  db_data:
  esdata:
    driver: local

networks:
  local:
    driver: bridge
