version: '3.1'

services:
  api_merchant:
    restart: always
    container_name: api_merchant
    build:
      context: .
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 2358:2345
    depends_on:
      - db
    networks:
      - shared_network

networks:
  shared_network:
    external: true
