version: '3.1'

services:

  api_merchant:
    restart: always
    container_name: api_merchant
    build:
      context: .
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 2358:2345
    depends_on:
      - db
    networks:
      - shared_network

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.13.3'
    container_name: elasticsearch_merchant
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9400:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - shared_network

volumes:
  esdata:
    driver: local

networks:
  shared_network:
    external: true
